#pragma once

namespace feather::utils
{
    enum class FEATHER_MODE
    {
        ACTION_MODE = 0,
        ACTION_MODE_COLOR,
        ACTION_MODE_COPY_UNTIL,
        ACTION_MODE_DROP_BREAKPOINTS,
        ACTION_MODE_RELOAD,
        ACTION_MODE_REMOVE_UNTIL,
        ACTION_MODE_REPLACE_ALL,
        ACTION_MODE_SAVE,
        ACTION_MODE_SAVING_IN_PROGRESS,
        ACTION_MODE_STASH_CHANGES,
        ACTION_MODE_UNCOLOR,
        BROWSE_SEARCH_RESULT_DOWN_MODE,
        BROWSE_SEARCH_RESULT_MODE,
        BROWSE_SEARCH_RESULT_UP_MODE,
        HEX_SEARCH_MODE,
        READ_MODE,
        READ_MODE_SELECT_TEXT,
        READ_MODE_WAITING_FOR_INPUT,
        SEARCHING_IN_PROGRESS_DOWN,
        SEARCHING_IN_PROGRESS_UP,
        SEARCH_MODE,
        SHORTCUTS_READ_MODE,
        SHORTCUTS_WRITE_MODE,
        TRIAL_TIMEOUT,
        WORKING_MODE,
        WRITE_MODE
    };
}