#pragma once

namespace feather::action
{
    enum class ACTION_TYPE
    {
        ALIGN_TO_MIDDLE,
        COPY_LINE_ACTION,
        CUT_LINE_ACTION,
        HIGHLIGHT_BETWEEN_BRACKETS,
        HIGHLIGHT_LINE,
        MOVE_TO_BYTE_ACTION,
        MOVE_TO_FILE_BEGINING_ACTION,
        MOVE_TO_FILE_END_ACTION,
        MOVE_TO_LINE_BEGINING_ACTION,
        MOVE_TO_LINE_END_ACTION,
        MOVE_TO_LINE_END_WITH_EDIT_ACTION,
        MOVE_TO_NEXT_WORD_ACTION,
        MOVE_TO_PREVIOUS_WORD_ACTION,
        REMOVE_BETWEEN_BRACKETS,
        REMOVE_BETWEEN_WHITE_CHARACTERS,
        REMOVE_LINE_ACTION,
        REMOVE_MULTIPLE_LINES_ACTION,
        REMOVE_UNTIL_FILE_BEGIN_ACTION,
        REMOVE_UNTIL_FILE_END_ACTION,
        REMOVE_WORD_FORWARD_ACTION,
        SAVE_CHANGES_ACTION,
        SEARCH_SUBSTRING_ACTION,
        UNKNOWN
    };
}